# Generated by Django 2.2.11 on 2020-03-19 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('supplementType', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='supplements/')),
                ('details', models.CharField(max_length=300)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
