# Generated by Django 2.2.11 on 2020-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='image',
            field=models.ImageField(upload_to='Shop/static/images/supplements/'),
        ),
    ]
