# Generated by Django 2.2.11 on 2020-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='image',
            field=models.ImageField(upload_to='supplements'),
        ),
    ]
